//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;

namespace WebAPI_Training.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoteModelContainer : DbContext
    {
        public NoteModelContainer()
            : base("name=NoteModelContainer")
        {
            Database.SetInitializer(null);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Note> NoteSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
    }

    public class NoteModelContainerInitializer : DropCreateDatabaseIfModelChanges<NoteModelContainer>
    {
        protected override void Seed(NoteModelContainer context)
        {
            IList<Category> defaultCategories = new List<Category>();
            defaultCategories.Add(new Category(){Name = "Work"});
            defaultCategories.Add(new Category(){Name = "Home"});
            foreach (var category in defaultCategories)
            {
                context.CategorySet.Add(category);
            }

            base.Seed(context);
        }
    }
}
